
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.stone_type]

		[types.stone_type.twigs]
			rhyolite = true
			schist = true
			bloodstone = true
			silt = true

		[types.stone_type.atmospheric]
			dolerite = true
			ivory_travertine = true
			peach_travertine = true
			persimmon_travertine = true
			saffron_travertine = true

		[types.stone_type.caverns_and_chasms]
			sugilite = true

		[types.stone_type.biomeswevegone]
			white_sandstone = true
			blue_sandstone = true
			black_sandstone = true
			purple_sandstone = true
			pink_sandstone = true
			windswept_sandstone = true
			red_rock = true
			dacite = true
			mossy_stone = true
			rocky_stone = true

		[types.stone_type.create]
			limestone = true
			asurine = true
			crimsite = true
			ochrum = true
			veridium = true
			scoria = true
			scorchia = true

		[types.stone_type.aether_redux]
			sentrite = true
			divinite = true
			driftshale = true

		[types.stone_type.deep_aether]
			clorite = true
			raw_clorite = true
			aseterite = true
			nimbus_stone = true

		[types.stone_type.alexscaves]
			galena = true
			radrock = true
			abyssmarine = true
			guanostone = true
			limestone = true

		[types.stone_type.quark]
			soul_sandstone = true
			midori = true
			duskbound = true
			limestone = true
			jasper = true
			shale = true
			myalite = true
			permafrost = true
			shingles = true

		[types.stone_type.spelunkery]
			nephrite = true

		[types.stone_type.midnight]
			nightstone = true
			trenchstone = true
			rockshroom = true

		[types.stone_type.aether]
			holystone = true
			carved_stone = true
			angelic_stone = true
			hellfire_stone = true

		[types.stone_type.lost_aether_content]
			gale_stone = true

		[types.stone_type.ancient_aether]
			aerogetic_stone = true

		[types.stone_type.deeperdarker]
			sculk_stone = true
			gloomslate = true

		[types.stone_type.undergarden]
			depthrock = true
			shiverstone = true
			tremblecrust = true

		[types.stone_type.wizards_reborn]
			wisestone = true

		[types.stone_type.rubinated_nether]
			altar_stone = true

		[types.stone_type.upgrade_aquatic]
			coralstone = true

		[types.stone_type.supplementaries]
			ash = true

		[types.stone_type.wetland_whimsy]
			limestone = true

		[types.stone_type.forbidden_arcanus]
			darkstone = true

		[types.stone_type.arts_and_crafts]
			gypsum = true
			soapstone = true

	[types.mud_type]

		[types.mud_type.deeperdarker]
			sculk_grime = true

		[types.mud_type.deep_aether]
			aether_mud = true

	[types.wood_type]

		[types.wood_type.netherexp]
			claret = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.hexalia]
			cottonwood = true
			willow = true

		[types.wood_type.moresnifferflowers]
			corrupted = true
			vivicus = true

		[types.wood_type.midnight]
			shadowroot = true
			dark_willow = true
			decayed = true
			manglewood = true
			nightshroom = true
			dewshroom = true
			viridshroom = true
			moonshroom = true
			bogshroom = true

		[types.wood_type.aether]
			skyroot = true

		[types.wood_type.deep_aether]
			roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.wood_type.ancient_aether]
			highsproot = true
			sakura = true

		[types.wood_type.aether_redux]
			fieldsproot = true
			blightwillow = true
			cloudcap = true
			jellyshroom = true
			crystal = true
			glacia = true

		[types.wood_type.snifferplus]
			stone_pine = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.deeperdarker]
			echo = true
			bloom = true

		[types.wood_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.wood_type.sullysmod]
			petrified = true

		[types.wood_type.environmental]
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.wood_type.autumnity]
			maple = true

		[types.wood_type.wizards_reborn]
			arcane_wood = true
			innocent_wood = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.endergetic]
			poise = true

		[types.wood_type.eidolon]
			illwood = true

		[types.wood_type.caverns_and_chasms]
			azalea = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

		[types.wood_type.malum]
			runewood = true
			soulwood = true

		[types.wood_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			florus = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			sakura = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true

		[types.wood_type.spawn]
			rotten = true

		[types.wood_type.wetland_whimsy]
			bald_cypress = true

		[types.wood_type.forbidden_arcanus]
			fungyss = true
			aurum = true
			edelwood = true

		[types.wood_type.betterarcheology]
			rotten = true

		[types.wood_type.ender_remastered]
			deep = true

		[types.wood_type.habitat]
			fairy_ring_mushroom = true

		[types.wood_type.arts_and_crafts]
			cork = true

	[types.leaves_type]

		[types.leaves_type.environmental]
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true
			cheerful_plum = true
			moody_plum = true
			hibiscus = true
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.leaves_type.aether]
			golden_oak = true
			holiday = true
			decorated_holiday = true
			crystal = true
			crystal_fruit = true
			skyroot = true

		[types.leaves_type.aether_redux]
			fieldsproot = true
			gilded_oak = true
			blighted_skyroot = true
			purple_glacia = true
			blightwillow = true
			glacia = true

		[types.leaves_type.deep_aether]
			flowering_roseroot = true
			blue_roseroot = true
			flowering_blue_roseroot = true
			roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.leaves_type.ancient_aether]
			crystal_skyroot = true
			enchanted_skyroot = true
			skyroot_pine = true
			blue_skyroot_pine = true
			highsproot = true
			sakura = true

		[types.leaves_type.autumnity]
			yellow_maple = true
			orange_maple = true
			red_maple = true
			maple = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.hexalia]
			cottonwood = true
			willow = true

		[types.leaves_type.moresnifferflowers]
			corrupted = true
			vivicus = true

		[types.leaves_type.midnight]
			shadowroot = true
			dark_willow = true
			manglewood = true

		[types.leaves_type.snifferplus]
			stone_pine = true

		[types.leaves_type.deeperdarker]
			echo = true

		[types.leaves_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.leaves_type.wizards_reborn]
			arcane_wood = true
			innocent_wood = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.eidolon]
			illwood = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.malum]
			runewood = true
			azure_runewood = true
			soulwood = true
			budding_soulwood = true

		[types.leaves_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true
			palo_verde = true
			araucaria = true
			ripe_baobab = true
			flowering_baobab = true
			blue_spruce = true
			blooming_witch_hazel = true
			brown_birch = true
			brown_oak = true
			brown_zelkova = true
			ripe_orchard = true
			flowering_orchard = true
			flowering_palo_verde = true
			holly_berry = true
			indigo_jacaranda = true
			flowering_jacaranda = true
			flowering_indigo_jacaranda = true
			yucca = true
			ripe_yucca = true
			flowering_yucca = true
			orange_birch = true
			orange_oak = true
			orange_spruce = true
			orchard = true
			red_birch = true
			red_maple = true
			red_oak = true
			red_spruce = true
			silver_maple = true
			green_apple_skyris = true
			flowering_skyris = true
			flowering_ironwood = true
			white_sakura = true
			yellow_sakura = true
			yellow_birch = true
			yellow_spruce = true
			firecracker = true

		[types.leaves_type.wetland_whimsy]
			bald_cypress = true

		[types.leaves_type.forbidden_arcanus]
			aurum = true
			nuggety_aurum = true

		[types.leaves_type.arts_and_crafts]
			cork = true

#Disables specific entries
[entries]

	[entries.stone_type]

		[entries.stone_type.create]
			small_brick_wall = true
			cut_wall = true
			small_bricks = true
			cut_brick_slab = true
			polished_cut_slab = true
			small_brick_stairs = true
			cut_bricks = true
			cut = true
			polished_cut = true
			small_brick_slab = true
			layered = true
			polished_cut_stairs = true
			cut_brick_wall = true
			pillar = true
			cut_stairs = true
			cut_brick_stairs = true
			polished_cut_wall = true
			cut_slab = true

		[entries.stone_type.quark]
			polished_vertical_slab = true
			pillar = true
			vertical_slab = true

		[entries.stone_type.twigs]
			column = true

	[entries.mud_type]

		[entries.mud_type.quark]
			carved_bricks = true
			pillar = true
			brick_lattice = true

		[entries.mud_type.betterarcheology]
			cracked_brick_stairs = true
			cracked_bricks = true
			cracked_brick_slab = true

	[entries.wood_type]

		[entries.wood_type.woodworks]
			bookshelf = true
			chiseled_bookshelf = true
			trapped_chest = true
			boards = true
			chest = true
			ladder = true
			beehive = true

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			hollow_log = true
			vertical_slab = true

		[entries.wood_type.twigs]
			table = true

		[entries.wood_type.friendsandfoes]
			beehive = true

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.create]
			window = true
			window_pane = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.woodworks]
			leaf_pile = true

